networks:
  booking_system:

services:
  server:
    build:
      dockerfile: ./docker/dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    container_name: booking_system_server
    networks:
      - booking_system
  php:
    build:
      dockerfile: ./docker/dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html:delegated
    container_name: booking_system_php
    networks:
      - booking_system
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: booking_system_mysql
    env_file:
      - ./docker/mysql/.env
    ports:
      - 3306:3306
    networks:
      - booking_system
    volumes:
      - /opt/mysql_data:/var/lib/mysql

  composer:
    build:
      dockerfile: ./docker/dockerfiles/composer.dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - booking_system
  artisan:
    build:
      dockerfile: ./docker/dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - booking_system
  scheduler:
    build:
      dockerfile: ./docker/dockerfiles/php.dockerfile
    container_name: booking_system_scheduler
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan", "schedule:work" ]
    networks:
      - booking_system

